/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue Token
         * @description 签发 JWT（二选一凭证：api_key 兑换或用户密码）。
         *
         *     Args:
         *         request: 兑换请求（grant_type=api_key | password）。
         *
         *     Returns:
         *         TokenResponse: access_token + 有效期 + 用户信息。
         *
         *     Raises:
         *         HTTPException: AUTH_400_BAD_CREDENTIALS（凭证错误）/
         *             AUTH_401_INVALID_API_KEY / AUTH_429_RATE_LIMITED（兑换限流更严）。
         */
        post: operations["issue_token_api_v1_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description 当前用户会话列表（游标分页）。
         *
         *     title 为该会话首条用户消息截断（≤30 字符）。
         *
         *     Args:
         *         cursor: 分页游标。
         *         limit: 每页数量。
         *
         *     Returns:
         *         Paged[SessionSummary]: 会话摘要列表。
         */
        get: operations["list_sessions_api_v1_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Messages
         * @description 会话历史消息（聚合 thread checkpoint 与工作记忆）。
         *
         *     Args:
         *         session_id: 会话 ID。
         *         cursor: 分页游标。
         *         limit: 每页数量（默认 50）。
         *
         *     Returns:
         *         Paged[SessionMessage]: 历史消息列表。
         *
         *     Raises:
         *         HTTPException: SESSION_404_NOT_FOUND（不存在或非本人，他人返回 404）。
         */
        get: operations["get_session_messages_api_v1_sessions__session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description 删除会话及其记忆。
         *
         *     行为：删除 thread checkpoint + 工作记忆 List + 该 session 的
         *     情景记忆 points（异步级联，A-05）。
         *
         *     Args:
         *         session_id: 会话 ID。
         *
         *     Raises:
         *         HTTPException: SESSION_404_NOT_FOUND。
         */
        delete: operations["delete_session_api_v1_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Feedback
         * @description 上报点赞/点踩。
         *
         *     Args:
         *         request: 反馈请求（rating ∈ up|down；reason 仅 down 必填）。
         *
         *     Returns:
         *         FeedbackResponse: 受理结果。
         *
         *     Raises:
         *         HTTPException: FEEDBACK_404_MESSAGE_NOT_FOUND。
         */
        post: operations["submit_feedback_api_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/subgraph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Subgraph
         * @description 按实体查询可视化子图（@neo4j-nvl/react 直接可用格式）。
         *
         *     Args:
         *         entity: 规范实体名（必填）。
         *         depth: 扩展深度（默认 2，上限 3）。
         *         limit: 节点数量上限（默认 50，上限 200）。
         *         client: Neo4j 客户端。
         *
         *     Returns:
         *         SubgraphResponse: {nodes[], relationships[]}。
         *
         *     Raises:
         *         ApiError: GRAPH_404_ENTITY_NOT_FOUND / GRAPH_503_STORE_UNAVAILABLE。
         */
        get: operations["get_subgraph_api_v1_graph_subgraph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Config
         * @description 下发公共配置（模型条目/档位/压缩策略/Profile）。
         *
         *     Returns:
         *         PublicConfig: 前端下拉框与档位选择所需枚举。
         */
        get: operations["get_public_config_api_v1_config_public_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/precheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Precheck
         * @description L1 语义缓存短路查询（J22/H2，单元 8.3 S1）。
         *
         *     查询向量 ANN 检索 Qdrant rag_cache，score >= 0.95 命中：
         *     - 命中返回 {hit:true, answer, citations, cache_score, matched_query}
         *     - 未命中返回 {hit:false, suggested_run}（意图启发式建议档位）
         *
         *     缓存永不阻塞主链路：Qdrant/Embedding 异常时返回 {hit:false}
         *     并置 X-Degraded: no-cache，不报错（07 A-11）。
         *
         *     Args:
         *         request: precheck 请求（query + session_id）。
         *         response: FastAPI 响应（用于置 X-Degraded 头）。
         *         cache: 语义缓存（依赖注入）。
         *
         *     Returns:
         *         PrecheckResponse: 命中/未命中两态。
         */
        post: operations["chat_precheck_api_v1_chat_precheck_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/cache/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear Cache
         * @description 按 scope/doc_id 清除缓存（失效联动）。
         *
         *     Args:
         *         request: 清理范围与可选 doc_id。
         *
         *     Returns:
         *         CacheClearResponse: 清除条目数。
         */
        post: operations["clear_cache_api_v1_admin_cache_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/index/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rebuild Index
         * @description 触发索引异步重建（vector/graph/fulltext/all）。
         *
         *     Args:
         *         request: 重建范围与是否全量。
         *
         *     Returns:
         *         TaskAccepted: 任务 ID（进度查 GET /admin/tasks/{task_id}）。
         *
         *     Raises:
         *         HTTPException: ADMIN_409_TASK_RUNNING（已有重建任务执行中）。
         */
        post: operations["rebuild_index_api_v1_admin_index_rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/config/hot-reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Hot Reload Config
         * @description J18 受限热更：清洗规则/检索权重/降级参数/agent.* 效率参数。
         *
         *     写回 YAML + pydantic 重校验，无需重启；分块参数与 embedding
         *     模型禁止热更（01 §7）。操作自动落审计日志（操作人/时间/diff）。
         *
         *     Returns:
         *         HotReloadResponse: 重载成功的配置与错误列表。
         */
        put: operations["hot_reload_config_api_v1_admin_config_hot_reload_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Review Queue
         * @description 开放区实体人工审核队列（J12，按出现频次排序）。
         *
         *     Args:
         *         cursor: 分页游标。
         *         limit: 每页数量。
         *
         *     Returns:
         *         Paged[ReviewQueueItem]: 待审核实体列表。
         */
        get: operations["list_review_queue_api_v1_admin_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/review/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Decision
         * @description 审核决定：approve 升级白名单并重放关联三元组；reject 拒绝。
         *
         *     Args:
         *         request: 实体 ID + 决定。
         *
         *     Returns:
         *         FeedbackResponse: {ok: true}。
         */
        post: operations["review_decision_api_v1_admin_review_decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Status
         * @description 查询异步任务进度（如索引重建）。
         *
         *     Args:
         *         task_id: 任务 ID。
         *
         *     Returns:
         *         TaskStatus: 状态与进度。
         */
        get: operations["get_task_status_api_v1_admin_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingestion/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Ingestion
         * @description 触发采集扫描（full | incremental）。
         *
         *     骨架阶段同步执行并返回扫描任务 ID；异步任务化随 admin
         *     任务体系（10.6 TaskProgressPanel）完善。
         *
         *     Args:
         *         request: 扫描模式与可选 source。
         *         service: 采集编排器。
         *
         *     Returns:
         *         TaskAccepted: task_id = 本次 scan_id。
         */
        post: operations["run_ingestion_api_v1_admin_ingestion_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ingestion/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scans
         * @description 扫描结果列表（新→旧，骨架阶段内存分页）。
         *
         *     Args:
         *         cursor: 分页游标（扫描记录偏移）。
         *         limit: 每页数量。
         *
         *     Returns:
         *         Paged[ScanRecord]: discovered/changed/deduped 变更计数。
         */
        get: operations["list_scans_api_v1_admin_ingestion_scans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/parsing/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parsing Preview
         * @description 解析预览：multipart 上传样例文件，或按 doc_id 取最近采集文档。
         *
         *     Args:
         *         doc_id: 已采集文档 ID（与 file 二选一）。
         *         file: 上传的样例文件（限 md/html/pdf）。
         *         service: 采集编排器（doc_id 查找用）。
         *
         *     Returns:
         *         ParsingPreviewResponse: text + structure_tree + format_meta。
         *
         *     Raises:
         *         HTTPException: 400 缺少输入或格式不支持。
         */
        post: operations["parsing_preview_api_v1_admin_parsing_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/cleaning/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cleaning Preview
         * @description 清洗前后对比预览。
         *
         *     Args:
         *         request: doc_id + 可选 rules_override。
         *         service: 采集编排器（按 doc_id 取最近采集文档）。
         *
         *     Returns:
         *         CleaningPreviewResponse: before/after/removed_spans/quality_score。
         *
         *     Raises:
         *         ApiError: SYS_404_NOT_FOUND（doc_id 不在最近批次）。
         */
        post: operations["cleaning_preview_api_v1_admin_cleaning_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/chunking/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chunking Preview
         * @description 分块边界预览：按 doc_id 取最近采集文档，解析→清洗→分块。
         *
         *     Args:
         *         request: doc_id。
         *         service: 采集编排器（按 doc_id 取最近采集文档）。
         *
         *     Returns:
         *         ChunkingPreviewResponse: chunks（含 chunk_id/content/title_path/position）。
         *
         *     Raises:
         *         ApiError: SYS_404_NOT_FOUND（doc_id 不在最近批次）。
         */
        post: operations["chunking_preview_api_v1_admin_chunking_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/debug/embed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Embed Probe
         * @description 向量探针：输入文本，返回 dense 维数 / sparse 键数 / 耗时。
         *
         *     Args:
         *         request: 探针文本。
         *         embedding: Embedding 服务。
         *
         *     Returns:
         *         EmbedProbeResponse: dense_dims / sparse_keys / latency_ms。
         *
         *     Raises:
         *         ApiError: SYS_503_DEPENDENCY_DOWN（Ollama/模型服务不可用）。
         */
        post: operations["embed_probe_api_v1_admin_debug_embed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/debug/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ik Analyze
         * @description IK 分词调试（封装 _analyze API）。
         *
         *     Args:
         *         request: 目标索引 + 待分词文本。
         *         es: ES 客户端。
         *
         *     Returns:
         *         IkAnalyzeResponse: 分词 token 列表。
         *
         *     Raises:
         *         ApiError: GRAPH_503_STORE_UNAVAILABLE（ES 不可用）。
         */
        post: operations["ik_analyze_api_v1_admin_debug_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/debug/retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Debug Retrieve
         * @description 六路检索调试（sources 过滤 + 分组返回 + 融合 Top-N，单元 3.5）。
         *
         *     六路：dense/sparse/graph/global/fulltext/web；fused 为融合三件套
         *     （去重 → RRF/加权融合）输出 Top-20。单路失败不阻塞其余路。
         *
         *     Args:
         *         request: 查询 + top_k + sources 过滤。
         *         qdrant: Qdrant 客户端。
         *         neo4j: Neo4j 客户端。
         *         es: ES 客户端。
         *         embedding: Embedding 服务。
         *
         *     Returns:
         *         DebugRetrieveResponse: 按源分组结果 + fused（当前为空）。
         *
         *     Raises:
         *         ApiError: DEBUG_400_INVALID_SOURCE（sources 含非法源）。
         */
        post: operations["debug_retrieve_api_v1_admin_debug_retrieve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/debug/rerank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Debug Rerank
         * @description 精排对比调试（02 §3.11，单元 4.1）。
         *
         *     FlagEmbedding 未安装/超时时自动 no-rerank 降级（degraded=true）。
         *
         *     Args:
         *         request: 查询 + 候选文档 + top_k。
         *         reranker: 精排器单例。
         *
         *     Returns:
         *         DebugRerankResponse: 精排后列表 + 降级标志 + 耗时。
         */
        post: operations["debug_rerank_api_v1_admin_debug_rerank_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/communities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Communities
         * @description 社区摘要列表（新→旧，按 level/成员数排序）。
         *
         *     Args:
         *         level: 层级过滤（0 叶子 / 1 父层；缺省全部）。
         *         cursor: 游标（偏移量字符串）。
         *         limit: 每页数量。
         *         client: Neo4j 客户端。
         *
         *     Returns:
         *         Paged[CommunitySummaryItem]。
         *
         *     Raises:
         *         ApiError: GRAPH_503_STORE_UNAVAILABLE（Neo4j 不可用）。
         */
        get: operations["list_communities_api_v1_admin_communities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/qdrant/points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Points
         * @description 按 doc_id 查询全部业务集合中的 points。
         *
         *     Args:
         *         doc_id: 文档 ID。
         *         limit: 每集合返回上限。
         *         client: Qdrant 客户端。
         *
         *     Returns:
         *         QdrantPointsResponse: points 列表（含 payload）。
         */
        get: operations["list_points_api_v1_admin_qdrant_points_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/golden/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Golden
         * @description 导出点踩 bad case 清单（CSV 流，golden 回流）。
         *
         *     Args:
         *         since: 仅导出该时间之后的记录（可选）。
         *
         *     Returns:
         *         StreamingResponse: text/csv 流。
         */
        get: operations["export_golden_api_v1_admin_golden_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description 基础健康检查。
         *
         *     Returns:
         *         HealthStatus: 各服务连接状态。
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness Check
         * @description 就绪检查，验证所有依赖服务的连通性。
         *
         *     Args:
         *         neo4j: Neo4j 客户端。
         *         qdrant: Qdrant 客户端。
         *         redis: Redis 客户端。
         *
         *     Returns:
         *         HealthStatus: 各服务实际连通状态。
         */
        get: operations["readiness_check_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Prometheus 指标抓取端点。
         *
         *     Returns:
         *         Response: text/plain 格式的指标文本（OpenMetrics 兼容）。
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthTokenRequest
         * @description POST /auth/token 请求（02 §3.1，二选一凭证）。
         *
         *     Attributes:
         *         grant_type: 兑换方式。
         *         api_key: API Key（grant_type=api_key）。
         *         username: 用户名（grant_type=password）。
         *         password: 密码（grant_type=password）。
         */
        AuthTokenRequest: {
            /**
             * Grant Type
             * @enum {string}
             */
            grant_type: "api_key" | "password";
            /** Api Key */
            api_key?: string | null;
            /** Username */
            username?: string | null;
            /** Password */
            password?: string | null;
        };
        /** Body_parsing_preview_api_v1_admin_parsing_preview_post */
        Body_parsing_preview_api_v1_admin_parsing_preview_post: {
            /** Doc Id */
            doc_id?: string | null;
            /** File */
            file?: string | null;
        };
        /**
         * CacheClearRequest
         * @description POST /admin/cache/clear 请求。
         *
         *     Attributes:
         *         scope: 清理范围（l1 语义缓存 / l2 检索缓存 / all）。
         *         doc_id: 可选，按 doc_id 反查清除受影响缓存（失效联动）。
         */
        CacheClearRequest: {
            /**
             * Scope
             * @default all
             * @enum {string}
             */
            scope: "l1" | "l2" | "all";
            /** Doc Id */
            doc_id?: string | null;
        };
        /**
         * CacheClearResponse
         * @description POST /admin/cache/clear 响应。
         *
         *     Attributes:
         *         purged: 清除的缓存条目数。
         */
        CacheClearResponse: {
            /**
             * Purged
             * @default 0
             */
            purged: number;
        };
        /**
         * Chunk
         * @description P4 分块层输出：文档块。
         *
         *     Attributes:
         *         chunk_id: 块 ID，格式 f"{doc_id}-{seq}"。
         *         doc_id: 父文档 ID。
         *         seq: 文档内顺序号。
         *         content: 块内容。
         *         title_path: 标题路径，如 ["清蒸鲈鱼", "操作步骤", "蒸制"]。
         *         position: 父文档内字符定位。
         *         metadata: 键名遵循 MetadataKeys 规范（架构 §3.2）。
         */
        Chunk: {
            /** Chunk Id */
            chunk_id: string;
            /** Doc Id */
            doc_id: string;
            /** Seq */
            seq: number;
            /** Content */
            content: string;
            /** Title Path */
            title_path?: string[];
            position: components["schemas"]["PositionMeta"];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * ChunkingPreviewRequest
         * @description POST /admin/chunking/preview 请求（02 §3.11，单元 2.1）。
         *
         *     Attributes:
         *         doc_id: 已采集文档 ID。
         */
        ChunkingPreviewRequest: {
            /** Doc Id */
            doc_id: string;
        };
        /**
         * ChunkingPreviewResponse
         * @description POST /admin/chunking/preview 响应（02 §3.11：chunks 含边界/title_path/position）。
         *
         *     Attributes:
         *         chunks: 分块列表（chunk 边界高亮与 title_path 展示用）。
         */
        ChunkingPreviewResponse: {
            /** Chunks */
            chunks?: components["schemas"]["Chunk"][];
        };
        /**
         * Citation
         * @description 引用标注（02 §5）。
         *
         *     Attributes:
         *         marker: 答案中的 [n] 编号。
         *         result_ids: 支撑该结论的证据 ID。
         *         quote: 原文摘录（可选）。
         */
        Citation: {
            /** Marker */
            marker: number;
            /** Result Ids */
            result_ids?: string[];
            /** Quote */
            quote?: string | null;
        };
        /**
         * CleaningPreviewRequest
         * @description POST /admin/cleaning/preview 请求（02 §3.11，单元 1.3）。
         *
         *     Attributes:
         *         doc_id: 已采集文档 ID。
         *         rules_override: 可选规则子集（按名称过滤，缺省全部启用规则）。
         */
        CleaningPreviewRequest: {
            /** Doc Id */
            doc_id: string;
            /** Rules Override */
            rules_override?: string[] | null;
        };
        /**
         * CleaningPreviewResponse
         * @description POST /admin/cleaning/preview 响应（02 §3.11：before/after/removed_spans/quality_score）。
         *
         *     Attributes:
         *         before: 清洗前文本（解析态）。
         *         after: 清洗后文本。
         *         removed_spans: 被删除的行片段（diff 高亮用）。
         *         quality_score: 质量门控评分 [0,1]。
         */
        CleaningPreviewResponse: {
            /** Before */
            before: string;
            /** After */
            after: string;
            /** Removed Spans */
            removed_spans?: string[];
            /**
             * Quality Score
             * @default 0
             */
            quality_score: number;
        };
        /**
         * CommunitySummaryItem
         * @description GET /admin/communities items（02 §3.11，单元 2.6）。
         *
         *     Attributes:
         *         community_id: 社区 ID。
         *         level: 层级。
         *         summary: 社区摘要。
         *         size: 成员数。
         */
        CommunitySummaryItem: {
            /** Community Id */
            community_id: string;
            /**
             * Level
             * @default 0
             */
            level: number;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Size
             * @default 0
             */
            size: number;
        };
        /**
         * DebugRerankDoc
         * @description POST /admin/debug/rerank 候选文档条目（02 §3.11，单元 4.1）。
         *
         *     Attributes:
         *         content: 文档内容。
         */
        DebugRerankDoc: {
            /** Content */
            content: string;
        };
        /**
         * DebugRerankRankedItem
         * @description 精排结果条目。
         *
         *     Attributes:
         *         content: 文档内容。
         *         score: 精排分（降级时为粗排分）。
         */
        DebugRerankRankedItem: {
            /** Content */
            content: string;
            /** Score */
            score: number;
        };
        /**
         * DebugRerankRequest
         * @description POST /admin/debug/rerank 请求。
         *
         *     Attributes:
         *         query: 查询文本。
         *         docs: 候选文档列表。
         *         top_k: 精排后保留数量。
         */
        DebugRerankRequest: {
            /** Query */
            query: string;
            /** Docs */
            docs: components["schemas"]["DebugRerankDoc"][];
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /**
         * DebugRerankResponse
         * @description POST /admin/debug/rerank 响应（精排对比）。
         *
         *     Attributes:
         *         ranked: 精排后列表（按分降序）。
         *         degraded: 是否 no-rerank 降级。
         *         elapsed_ms: 精排耗时（毫秒）。
         */
        DebugRerankResponse: {
            /** Ranked */
            ranked?: components["schemas"]["DebugRerankRankedItem"][];
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
        };
        /**
         * DebugRetrieveRequest
         * @description POST /admin/debug/retrieve 请求（02 §3.11，单元 3.3-3.5）。
         *
         *     Attributes:
         *         query: 查询文本。
         *         top_k: 每路返回数量（默认 10）。
         *         sources: 检索源过滤（六路枚举子集，缺省全选）。
         */
        DebugRetrieveRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
            /** Sources */
            sources?: components["schemas"]["SourceKind"][] | null;
        };
        /**
         * DebugRetrieveResponse
         * @description POST /admin/debug/retrieve 响应（02 §7 DebugRetrieveResponse）。
         *
         *     Attributes:
         *         results: 按检索源分组的结果（source -> RetrievalResult 列表）。
         *         fused: 融合后 Top-N（result_id + content，3.5 接入）。
         */
        DebugRetrieveResponse: {
            /** Results */
            results?: {
                [key: string]: components["schemas"]["RetrievalResult"][];
            };
            /** Fused */
            fused?: {
                [key: string]: string;
            }[];
        };
        /**
         * EmbedProbeRequest
         * @description POST /admin/debug/embed 请求（02 §3.11，单元 2.3）。
         *
         *     Attributes:
         *         text: 探针文本。
         */
        EmbedProbeRequest: {
            /** Text */
            text: string;
        };
        /**
         * EmbedProbeResponse
         * @description POST /admin/debug/embed 响应（向量探针：dense 维数 / sparse 键数 / 耗时）。
         *
         *     Attributes:
         *         dense_dims: 密集向量维度（BGE-M3 = 1024）。
         *         sparse_keys: 稀疏向量非零键数（FlagEmbedding 未接入时为 0）。
         *         latency_ms: 双通道向量化耗时（毫秒）。
         */
        EmbedProbeResponse: {
            /**
             * Dense Dims
             * @default 0
             */
            dense_dims: number;
            /**
             * Sparse Keys
             * @default 0
             */
            sparse_keys: number;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
        };
        /**
         * FeedbackRequest
         * @description POST /feedback 请求（02 §3.5，在线评估闭环数据源）。
         *
         *     Attributes:
         *         session_id: 会话 ID。
         *         message_id: 消息 ID。
         *         rating: 点赞/点踩。
         *         reason: 点踩原因（仅 down 必填）。
         *         comment: 补充说明。
         */
        FeedbackRequest: {
            /** Session Id */
            session_id: string;
            /** Message Id */
            message_id: string;
            /**
             * Rating
             * @enum {string}
             */
            rating: "up" | "down";
            /** Reason */
            reason?: ("wrong" | "incomplete" | "unsafe" | "other") | null;
            /** Comment */
            comment?: string | null;
        };
        /**
         * FeedbackResponse
         * @description POST /feedback 响应（02 §3.5）。
         *
         *     Attributes:
         *         ok: 是否受理成功。
         */
        FeedbackResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /**
         * GraphNode
         * @description 图谱子图节点（02 §3.6，NVL 直连格式）。
         *
         *     Attributes:
         *         id: 节点 ID。
         *         label: 显示名（canonical_name）。
         *         type: 实体类型。
         *         zone: 白名单/开放区（J12）。
         */
        GraphNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Type */
            type: string;
            /**
             * Zone
             * @default open
             * @enum {string}
             */
            zone: "core" | "open";
        };
        /**
         * GraphRelationship
         * @description 图谱子图关系边（02 §3.6）。
         *
         *     Attributes:
         *         source: 头节点 ID。
         *         target: 尾节点 ID。
         *         type: 关系类型。
         */
        GraphRelationship: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthComponent
         * @description 单组件健康状态（02 §3.9）。
         *
         *     Attributes:
         *         status: 组件状态。
         *         latency_ms: 探测耗时（毫秒）。
         *         detail: 异常详情。
         */
        HealthComponent: {
            /**
             * Status
             * @enum {string}
             */
            status: "up" | "degraded" | "down";
            /** Latency Ms */
            latency_ms?: number | null;
            /** Detail */
            detail?: string | null;
        };
        /**
         * HealthStatus
         * @description 健康聚合响应（02 §3.9，/health 与 /ready 共用）。
         *
         *     Attributes:
         *         status: 聚合状态（ready 为就绪）。
         *         components: 七组件探测结果（postgres/qdrant/neo4j/elasticsearch/
         *             redis/langgraph-server/ollama）。
         */
        HealthStatus: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Components */
            components?: {
                [key: string]: components["schemas"]["HealthComponent"];
            };
        };
        /**
         * HotReloadResponse
         * @description PUT /admin/config/hot-reload 响应（J18 受限热更）。
         *
         *     Attributes:
         *         reloaded: 重载成功的配置文件名。
         *         errors: 重载错误列表。
         */
        HotReloadResponse: {
            /** Reloaded */
            reloaded?: string[];
            /** Errors */
            errors?: string[];
        };
        /**
         * IkAnalyzeRequest
         * @description POST /admin/debug/analyze 请求（02 §3.11，单元 3.2）。
         *
         *     Attributes:
         *         index: 目标索引（rag_entities | rag_chunks）。
         *         text: 待分词文本。
         */
        IkAnalyzeRequest: {
            /**
             * Index
             * @default rag_entities
             * @enum {string}
             */
            index: "rag_entities" | "rag_chunks";
            /** Text */
            text: string;
        };
        /**
         * IkAnalyzeResponse
         * @description POST /admin/debug/analyze 响应（IK 分词调试）。
         *
         *     Attributes:
         *         tokens: 分词 token 列表。
         */
        IkAnalyzeResponse: {
            /** Tokens */
            tokens?: string[];
        };
        /**
         * IndexRebuildRequest
         * @description POST /admin/index/rebuild 请求。
         *
         *     Attributes:
         *         scope: 重建范围。
         *         full: 是否全量重建。
         */
        IndexRebuildRequest: {
            /**
             * Scope
             * @default all
             * @enum {string}
             */
            scope: "vector" | "graph" | "fulltext" | "all";
            /**
             * Full
             * @default true
             */
            full: boolean;
        };
        /**
         * IngestionRunRequest
         * @description POST /admin/ingestion/run 请求（02 §3.11，单元 1.1）。
         *
         *     Attributes:
         *         mode: 全量或增量扫描（架构 P1 文件发现策略）。
         *         source: 可选数据源标识（缺省用 pipeline_config 全部 sources）。
         */
        IngestionRunRequest: {
            /**
             * Mode
             * @default incremental
             * @enum {string}
             */
            mode: "full" | "incremental";
            /** Source */
            source?: string | null;
        };
        /**
         * LatencyTier
         * @description 延迟档位（D4 三档策略）。
         * @enum {string}
         */
        LatencyTier: "fast" | "standard" | "deep";
        /**
         * ModelOption
         * @description 可选模型条目（02 §3.7）。
         *
         *     Attributes:
         *         id: 注册表条目名（请求参数可引用）。
         *         label: 展示名。
         *         provider: 提供方（云端/本地）。
         */
        ModelOption: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "cloud" | "local";
        };
        /** Paged[CommunitySummaryItem] */
        Paged_CommunitySummaryItem_: {
            /** Items */
            items?: components["schemas"]["CommunitySummaryItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Paged[ReviewQueueItem] */
        Paged_ReviewQueueItem_: {
            /** Items */
            items?: components["schemas"]["ReviewQueueItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Paged[ScanRecord] */
        Paged_ScanRecord_: {
            /** Items */
            items?: components["schemas"]["ScanRecord"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Paged[SessionMessage] */
        Paged_SessionMessage_: {
            /** Items */
            items?: components["schemas"]["SessionMessage"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Paged[SessionSummary] */
        Paged_SessionSummary_: {
            /** Items */
            items?: components["schemas"]["SessionSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * ParsingPreviewResponse
         * @description POST /admin/parsing/preview 响应（02 §3.11，单元 1.2）。
         *
         *     Attributes:
         *         text: 解析出的纯文本。
         *         structure_tree: 标题层级树。
         *         format_meta: 格式元信息（format/encoding/page_count 等）。
         */
        ParsingPreviewResponse: {
            /** Text */
            text: string;
            /** Structure Tree */
            structure_tree?: components["schemas"]["StructureNode"][];
            /** Format Meta */
            format_meta?: {
                [key: string]: unknown;
            };
        };
        /**
         * PositionMeta
         * @description 块在父文档内的字符定位。
         *
         *     Attributes:
         *         start_char: 起始字符偏移。
         *         end_char: 结束字符偏移（不含）。
         */
        PositionMeta: {
            /** Start Char */
            start_char: number;
            /** End Char */
            end_char: number;
        };
        /**
         * PrecheckRequest
         * @description POST /chat/precheck 请求（02 §3.8，J22 语义缓存短路）。
         *
         *     Attributes:
         *         query: 查询文本。
         *         session_id: 会话 ID。
         */
        PrecheckRequest: {
            /** Query */
            query: string;
            /** Session Id */
            session_id?: string | null;
        };
        /**
         * PrecheckResponse
         * @description POST /chat/precheck 响应（02 §3.8 命中/未命中两态）。
         *
         *     Attributes:
         *         hit: 是否命中缓存（score >= 0.95，H2）。
         *         answer: 命中时的缓存答案。
         *         citations: 命中时的引用列表。
         *         cache_score: 命中时的相似度分数。
         *         matched_query: 命中时匹配的原始缓存查询。
         *         suggested_run: 未命中时的建议 run 参数。
         */
        PrecheckResponse: {
            /** Hit */
            hit: boolean;
            /** Answer */
            answer?: string | null;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /** Cache Score */
            cache_score?: number | null;
            /** Matched Query */
            matched_query?: string | null;
            suggested_run?: components["schemas"]["SuggestedRun"] | null;
        };
        /**
         * PublicConfig
         * @description GET /config/public 响应（J2「请求参数指定模型」的前端前提）。
         *
         *     Attributes:
         *         models: 可选模型条目清单。
         *         latency_tiers: 延迟档位枚举。
         *         compression_strategies: 压缩策略枚举（J11）。
         *         profile: 运行 Profile（cloud-primary / local）。
         */
        PublicConfig: {
            /** Models */
            models?: components["schemas"]["ModelOption"][];
            /** Latency Tiers */
            latency_tiers?: string[];
            /** Compression Strategies */
            compression_strategies?: string[];
            /**
             * Profile
             * @default cloud-primary
             */
            profile: string;
        };
        /**
         * QdrantPointItem
         * @description Qdrant 点条目（02 §3.11 GET /admin/qdrant/points，单元 3.1）。
         *
         *     Attributes:
         *         id: Point ID。
         *         chunk_id: 关联块 ID（payload 同源，三方映射）。
         *         score: 检索分数（scroll 查询时为 None）。
         *         payload: 点负载（04 §3.1 键规范）。
         */
        QdrantPointItem: {
            /** Id */
            id: string;
            /**
             * Chunk Id
             * @default
             */
            chunk_id: string;
            /** Score */
            score?: number | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * QdrantPointsResponse
         * @description GET /admin/qdrant/points 响应。
         *
         *     Attributes:
         *         points: 按 doc_id 过滤的点列表。
         */
        QdrantPointsResponse: {
            /** Points */
            points?: components["schemas"]["QdrantPointItem"][];
        };
        /**
         * RetrievalResult
         * @description 所有检索器（dense/sparse/graph/global/fulltext/web）的统一输出。
         *
         *     Attributes:
         *         result_id: 全局唯一结果标识，融合层去重键，格式 f"{name}:{stable_hash}"。
         *         chunk_id: 关联块 ID（图谱/Web 结果可为 None）。
         *         content: 文本片段或子图序列化文本。
         *         score: 原始分数（归一化前，口径见各检索器 docstring）。
         *         source: 检索来源（六路枚举）。
         *         doc_id: 关联父文档，支持上下文扩展。
         *         metadata: 附加元数据（键名遵循 MetadataKeys）。
         */
        RetrievalResult: {
            /** Result Id */
            result_id: string;
            /** Chunk Id */
            chunk_id?: string | null;
            /** Content */
            content: string;
            /** Score */
            score: number;
            source: components["schemas"]["SourceKind"];
            /** Doc Id */
            doc_id?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * ReviewDecisionRequest
         * @description POST /admin/review/decision 请求。
         *
         *     Attributes:
         *         entity_id: 待审核实体 ID。
         *         action: approve 升级白名单并重放关联三元组；reject 拒绝。
         */
        ReviewDecisionRequest: {
            /** Entity Id */
            entity_id: string;
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "reject";
        };
        /**
         * ReviewQueueItem
         * @description 开放区人工审核队列条目（J12，按出现频次排序）。
         *
         *     Attributes:
         *         entity_id: 实体 ID。
         *         name: 实体名。
         *         freq: 出现频次。
         *         first_seen: 首次发现时间。
         */
        ReviewQueueItem: {
            /** Entity Id */
            entity_id: string;
            /** Name */
            name: string;
            /**
             * Freq
             * @default 0
             */
            freq: number;
            /** First Seen */
            first_seen?: string | null;
        };
        /**
         * ScanRecord
         * @description 扫描结果记录（02 §3.11 GET /admin/ingestion/scans items，04 §2.3 水位联动）。
         *
         *     Attributes:
         *         scan_id: 扫描任务 ID。
         *         mode: 扫描模式。
         *         discovered: 发现的候选文件数。
         *         changed: 新增/变更文件数（增量判定依据 content_hash）。
         *         deduped: 内容哈希去重拦截数。
         *         finished_at: 完成时间（ISO 8601 UTC）。
         */
        ScanRecord: {
            /** Scan Id */
            scan_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "full" | "incremental";
            /**
             * Discovered
             * @default 0
             */
            discovered: number;
            /**
             * Changed
             * @default 0
             */
            changed: number;
            /**
             * Deduped
             * @default 0
             */
            deduped: number;
            /** Finished At */
            finished_at?: string | null;
        };
        /**
         * SessionMessage
         * @description 会话历史消息（02 §3.3，聚合 thread checkpoint 与工作记忆）。
         *
         *     Attributes:
         *         message_id: 消息 ID。
         *         role: 消息角色。
         *         content: 消息内容。
         *         created_at: 创建时间。
         *         citations: 引用列表（assistant 消息）。
         *         degraded: 该回答是否降级产出。
         *         latency_tier: 该回答的执行档位。
         *         model: 该回答使用的模型条目名。
         */
        SessionMessage: {
            /** Message Id */
            message_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            latency_tier?: components["schemas"]["LatencyTier"] | null;
            /** Model */
            model?: string | null;
        };
        /**
         * SessionSummary
         * @description 会话摘要（02 §3.2）。
         *
         *     Attributes:
         *         session_id: 会话 ID。
         *         title: 首条用户消息截断（≤30 字符）。
         *         message_count: 消息数。
         *         created_at: 创建时间（ISO 8601 UTC）。
         *         updated_at: 更新时间。
         */
        SessionSummary: {
            /** Session Id */
            session_id: string;
            /** Title */
            title: string;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SourceKind
         * @description 检索来源枚举（架构 §3.3 RetrievalResult.source 六路）。
         * @enum {string}
         */
        SourceKind: "dense" | "sparse" | "graph" | "global" | "fulltext" | "web";
        /**
         * StructureNode
         * @description 文档结构树节点（P2 解析层产出）。
         *
         *     Attributes:
         *         level: 标题层级（1 起）。
         *         title: 标题文本。
         *         start_offset: 该节在全文中的起始字符偏移。
         */
        StructureNode: {
            /** Level */
            level: number;
            /** Title */
            title: string;
            /**
             * Start Offset
             * @default 0
             */
            start_offset: number;
        };
        /**
         * SubgraphResponse
         * @description GET /graph/subgraph 响应（@neo4j-nvl/react 直接可用格式）。
         *
         *     Attributes:
         *         nodes: 节点列表。
         *         relationships: 关系边列表。
         */
        SubgraphResponse: {
            /** Nodes */
            nodes?: components["schemas"]["GraphNode"][];
            /** Relationships */
            relationships?: components["schemas"]["GraphRelationship"][];
        };
        /**
         * SuggestedRun
         * @description precheck 未命中时的建议 run 参数。
         *
         *     Attributes:
         *         latency_tier: 意图分类轻量启发式给出的建议档位（前端可覆盖）。
         */
        SuggestedRun: {
            /** @default standard */
            latency_tier: components["schemas"]["LatencyTier"];
        };
        /**
         * TaskAccepted
         * @description 异步任务受理响应（202）。
         *
         *     Attributes:
         *         task_id: 任务 ID，进度查 GET /admin/tasks/{task_id}。
         */
        TaskAccepted: {
            /** Task Id */
            task_id: string;
        };
        /**
         * TaskStatus
         * @description GET /admin/tasks/{task_id} 响应。
         *
         *     Attributes:
         *         state: 任务状态。
         *         progress: 进度 [0,1]。
         */
        TaskStatus: {
            /**
             * State
             * @enum {string}
             */
            state: "running" | "done" | "failed";
            /**
             * Progress
             * @default 0
             */
            progress: number;
        };
        /**
         * TokenResponse
         * @description POST /auth/token 响应（02 §3.1）。
         *
         *     Attributes:
         *         access_token: JWT。
         *         token_type: 固定 bearer。
         *         expires_in: 有效期（秒）。
         *         user: 用户信息。
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @default 86400
             */
            expires_in: number;
            user: components["schemas"]["UserInfo"];
        };
        /**
         * UserInfo
         * @description 用户信息（随 token 响应下发）。
         *
         *     Attributes:
         *         id: 用户 ID。
         *         name: 用户名。
         *         role: 角色（admin 可访问 /admin/*）。
         */
        UserInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @default user
             * @enum {string}
             */
            role: "user" | "admin";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    issue_token_api_v1_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_sessions_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paged_SessionSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_messages_api_v1_sessions__session_id__messages_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paged_SessionMessage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_v1_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_api_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subgraph_api_v1_graph_subgraph_get: {
        parameters: {
            query: {
                /** @description 规范实体名（canonical_name） */
                entity: string;
                /** @description 扩展深度，上限 3 */
                depth?: number;
                /** @description 节点数上限 200 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubgraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_config_api_v1_config_public_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicConfig"];
                };
            };
        };
    };
    chat_precheck_api_v1_chat_precheck_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrecheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrecheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_cache_api_v1_admin_cache_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CacheClearRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CacheClearResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_index_api_v1_admin_index_rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexRebuildRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hot_reload_config_api_v1_admin_config_hot_reload_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotReloadResponse"];
                };
            };
        };
    };
    list_review_queue_api_v1_admin_review_queue_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paged_ReviewQueueItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_decision_api_v1_admin_review_decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_status_api_v1_admin_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_ingestion_api_v1_admin_ingestion_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IngestionRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scans_api_v1_admin_ingestion_scans_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paged_ScanRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parsing_preview_api_v1_admin_parsing_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parsing_preview_api_v1_admin_parsing_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsingPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cleaning_preview_api_v1_admin_cleaning_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleaningPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleaningPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chunking_preview_api_v1_admin_chunking_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChunkingPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkingPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    embed_probe_api_v1_admin_debug_embed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbedProbeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbedProbeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ik_analyze_api_v1_admin_debug_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IkAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IkAnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_retrieve_api_v1_admin_debug_retrieve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebugRetrieveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugRetrieveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_rerank_api_v1_admin_debug_rerank_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebugRerankRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugRerankResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_communities_api_v1_admin_communities_get: {
        parameters: {
            query?: {
                /** @description 层级过滤（缺省全部） */
                level?: number | null;
                /** @description 游标（偏移量） */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Paged_CommunitySummaryItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_points_api_v1_admin_qdrant_points_get: {
        parameters: {
            query: {
                /** @description 文档 ID */
                doc_id: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QdrantPointsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_golden_api_v1_admin_golden_export_get: {
        parameters: {
            query?: {
                /** @description ISO 时间过滤 */
                since?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    readiness_check_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
